/* TIEDS Q3 LABELS */

LABEL  
ID_NUM  =	"	Subject ID(6 digits) first=Center, next 4=ID, last=Individual ID"
StudyID	=	"	StudyID: used to merge TIDES data	"
USERID	=	"	USERID	"
Center	=	"	6=UCSF 7=UMN 8=URMC 9=UW"
Dropped = " Dropped from study, 1=yes 0=no"
Complete = " Complete questionnaire, 1=yes/0=no"
TIME_STAMP	=	"	TIME_STAMP	"
Q3_Date =" Date of questionnaire completed"

Q1_wks_recode	=	"Far along in pregnancy, recoded as weeks	"
Q1_wks	=	"	Far along in pregnancy, weeks	"
Q1_days	=	"	Far along in pregnancy, days	"
Q2_wt_lbs_recode	=	"Current weight, recoded as pounds	"
Q2_wt_lbs = "Current weight, pounds"
Q2_wt_kg = "Current weight, kg."
Q3_HEIGHT_CM = "Current height, cm"
Q3_HEIGHT_IN = "Current height, inches"
Q3_ht_in_recode = "Current height, recoded in inches"
Q4	=	"	Current health	"

Q5a	=	"	Any meds for a week, yes/no	"
Q5a1_a_yn	=	"	Allergy meds, yes/no	"
Q5a1_a_script	=	"	Allergy meds, prescription	"
Q5a1_a_otc	=	"	Allergy meds, over the counter	"
Q5a1_b_yn	=	"	Arthritis meds, yes/no	"
Q5a1_b_script	=	"	Arthritis meds, prescription	"
Q5a1_b_otc	=	"	Arthritis meds, over the counter	"
Q5a1_c_yn	=	"	Asthma meds, yes/no	"
Q5a1_c_script	=	"	Asthma meds, prescription	"
Q5a1_c_otc	=	"	Asthma meds, over the counter	"
Q5a1_d_yn	=	"	COPD meds, yes/no	"
Q5a1_d_script	=	"	COPD meds, prescription	"
Q5a1_d_otc	=	"	COPD meds, over the counter	"
Q5a1_e_yn	=	"	Depression meds, yes/no	"
Q5a1_e_script	=	"	Depression meds, prescription	"
Q5a1_e_otc	=	"	Depression meds, over the counter	"
Q5a1_f_yn	=	"	Diabetes meds, yes/no	"
Q5a1_f_script	=	"	Diabetes meds, prescription	"
Q5a1_f_otc	=	"	Diabetes meds, over the counter	"
Q5a1_g_yn	=	"	Breast/genital meds, yes/no	"
Q5a1_g_script	=	"	Breast/genital meds, prescription	"
Q5a1_g_otc	=	"	Breast/genital meds, over the counter	"
Q5a1_h_yn	=	"	GI meds, yes/no	"
Q5a1_h_script	=	"	GI meds, prescription	"
Q5a1_h_otc	=	"	GI meds, over the counter	"
Q5a1_i_yn	=	"	High BP meds, yes/no	"
Q5a1_i_script	=	"	High BP meds, prescription	"
Q5a1_i_otc	=	"	High BP meds, over the counter	"
Q5a1_j_yn	=	"	Nausea meds, yes/no	"
Q5a1_j_script	=	"	Nausea meds, prescription	"
Q5a1_j_otc	=	"	Nausea meds, over the counter	"
Q5a1_k_yn	=	"	Pain meds, yes/no	"
Q5a1_k_script	=	"	Pain meds, prescription	"
Q5a1_k_otc	=	"	Pain meds, over the counter	"
Q5a1_l_yn	=	"	Resp. infect. meds, yes/no	"
Q5a1_l_script	=	"	Resp. infect. meds, prescriptiion	"
Q5a1_l_otc	=	"	Resp. infect. meds, over the counter	"
Q5a1_m_yn	=	"	Thyroid meds, yes/no	"
Q5a1_m_script	=	"	Thyroid meds, prescription	"
Q5a1_m_otc	=	"	Thyroid meds, over the counter	"
Q5a1_n_yn	=	"	Urinary meds, yes/no	"
Q5a1_n_script	=	"	Urinary meds, prescription	"
Q5a1_n_otc	=	"	Urinary meds, over the counter	"
Q5a1_o_yn	=	"	Other meds, yes/no	"
Q5a1_o_script	=	"	Other meds, prescription	"
Q5a1_o_otc	=	"	Other meds, over the counter	"
Q5b	=	"	Prenatal vitamin, yes/no	"
Q5b1	=	"	Form of vitamin	"
Q5c	=	"	Nutritional supplements, yes/no	"
Q5c_a_yn	=	"	Supplement, multivitamin, yes/no	"
Q5c_a_form	=	"	Supplement, multivitamin, form	"
Q5c_b_yn	=	"	Supplement, iron, yes/no	"
Q5c_b_form	=	"	Supplement, iron, form	"
Q5c_c_yn	=	"	Supplement, calcium, yes/no	"
Q5c_c_form	=	"	Supplement, calcium, form	"
Q5c_d_yn	=	"	Supplement, amino acid, yes/no	"
Q5c_d_form	=	"	Supplement, amino acid, form	"
Q5c_e_yn	=	"	Supplement, herbal, yes/no	"
Q5c_e_form	=	"	Supplement, herbal, form	"
Q5c_f_yn	=	"	Supplement, vitamin A, yes/no	"
Q5c_f_form	=	"	Supplement, vitamin A, form	"
Q5c_g_yn	=	"	Supplement, vitamin C, yes/no	"
Q5c_g_form	=	"	Supplement, vitamin C, form	"
Q5c_h_yn	=	"	Supplement, vitamin D, yes/no	"
Q5c_h_form	=	"	Supplement, vitamin D, form	"
Q5c_i_yn	=	"	Supplement, vitamin E, yes/no	"
Q5c_i_form	=	"	Supplement, vitamin E, form	"
Q5c_j_yn	=	"	Supplement, vitamin K, yes/no	"
Q5c_j_form	=	"	Supplement, vitamin K, form	"
Q5c_k_yn	=	"	Supplement, fish oil, yes/no	"
Q5c_k_form	=	"	Supplement, fish oil, form	"
Q5c_l_yn	=	"	Supplement, other, yes/no	"
Q5c_l_form	=	"	Supplement, other, form	"
Q5c_m_yn	=	"	Supplement, not sure, yes/no	"
Q5c_m_form	=	"	Supplement, not sure, form	"

Q5d	=	"	Hospitalized since pregnant	"
Q5e	=	"	Chemo/radiation since pregnant	"
Q5f	=	"	Transdermal meds since pregnant	"
Q5g	=	"	Time-release capsule	"
Q5h	=	"	Inhaler	"
Q5i	=	"	IV	"
Q5j	=	"	Implant or shunt "
Q5ja	=	" If implant or shunt still inside, yes/no	"
Q5ja1	=	" How long the implant or shunt	"
Q5jb = " What kind of implant or shunt "
Q5k	=	"	Any medical procedure involving an IV, yes/no	"

Q6 = "Current due date"

Q7	=	" Any complications with this pregnancy , yes/no	"
Q7a_1 = " Anemia"
Q7a_2 = " Intrauterine growth restriction (baby measuring less than 10th percentile)"
Q7a_3 = " Anxiety/depression"
Q7a_4 = " Placenta previa, or abruption"
Q7a_5 = " Birth defect detected"
Q7a_6 = " Preeclampsia"
Q7a_7 = " Bleeding"
Q7a_8 = " Premature rupture of membranes (breaking or leaking water)"
Q7a_9 = " Cervical problem (shortening, thinning, dilation)"
Q7a_10 = " Preterm labor"
Q7a_11 = " Gestational Diabetes"
Q7a_12 = " Other"
Q7a_13 = " Hypertension" 

Q8	=	" Chemicals in the environment can pose health risks	"
Q9	=	" Chemicals in the environment are in so many things that it’s impossible to avoid them	"
Q10	=	" When I buy personal care products, I try to make sure they are ecofriendly or chemical-free or environmentally friendly	"
Q11	=	" When I buy things for my home (such as household cleaning products, furniture, and upholstery), I try to make sure they are ecofriendly or chemical-free or environmentally friendly. 	"
Q12	=	" When I buy or consume food, I try to make sure it is organic, ecofriendly or chemical-free or environmentally friendly	"


Q13	=	"	Description of typical diet	"
Q14	=	" Rate of consumption of organic food	"
Q15	=	" Rate of consumption of food that is grown, raised or caught by you/family	"
Q16 =   " Rate of consumption of unprocessed food "
Q16 =   " Rate of consumption of unprocessed food "
Q16a =  " Rate of consumption of canned fruits or veg "
Q16b =  " Rate of consumption of frozen fruits or veg "
Q16c =  " Rate of consumption of fresh fruits or veg "

Q17 = " Foods consumed in a typical week "
Q17a	=	"	Meals/week, peanut butter	"
Q17b	=	"	Meals/week, beef	"
Q17c	=	"	Meals/week, seafood	"
Q17d	=	"	Meals/week, poultry	"
Q17e	=	"	Meals/week, other meats	"
Q17f	=	"	Meals/week, spices	"
Q17g	=	"	Meals/week, oils, butter	"
Q17h	=	"	Meals/week, soy products	"
Q17i	=	"	Meals/week, dairy products	"
Q18 	=	"	Meals/week, restaurant	"
Q18a	=	"	Meals/week, fast food restaurant	"

Q19A_YN =	"	Cigarettes, yes/no	"
Q19b_yn	=	"	Red wine, yes/no	"
Q19c_yn	=	"	Other wine, yes/no	"
Q19d_yn	=	"	Beer, yes/no	"
Q19e_yn	=	" Recode: Liquor, yes/no	"
Q19f_yn	=	"	Caffeinated coffee, yes/no	"
Q19g_yn	=	"	Caffeinated tea, yes/no	"
Q19h_yn	=	"	Caffeinated soda, yes/no	"
Q19i_yn	=	"	Marijuana, yes/no	"
Q19j_yn	=	"	Cocaine, yes/no	"
Q19a_Day	=	"Recode: Cigarettes/day	"
Q19b_Day	=	" Red wine/day	"
Q19c_Day	=	" Other wine /day	"
Q19d_Day	=	" Beer/day	"
Q19e_Day	=	" Liquor/day	"
Q19f_Day	=	" Caffeinated coffee/day	"
Q19g_Day	=	" Caffeinated tea/day	"
Q19h_Day	=	" Caffeinated soda/day	"
Q19i_Day	=	" Marijuana/day	"
Q19j_Day	=	" Cocaine/day	"
Q19a_WEEK	=	" Cigarettes/week	"
Q19b_WEEK	=	" Red wine/week	"
Q19c_WEEK	=	" Other wine /week	"
Q19d_WEEK	=	" Beer/week	"
Q19e_WEEK	=	" Liquor/week	"
Q19f_WEEK	=	" Caffeinated coffee/week	"
Q19g_WEEK	=	" Caffeinated tea/week	"
Q19h_WEEK	=	" Caffeinated soda/week	"
Q19i_WEEK	=	" Marijuana/week	"
Q19j_WEEK	=	" Cocaine/week	"
Q19a_WKS_Recode	=	"Recode: Cigarettes/week	"
Q19b_WKS_Recode	=	"Recode: Red wine/week	"
Q19c_WKS_Recode	=	"Recode: Other wine /week	"
Q19d_WKS_Recode	=	"Recode: Beer/week	"
Q19e_WKS_Recode	=	"Recode: Liquor/week	"
Q19f_WKS_Recode	=	"Recode: Caffeinated coffee/week	"
Q19g_WKS_Recode	=	"Recode: Caffeinated tea/week	"
Q19h_WKS_Recode	=	"Recode: Caffeinated soda/week	"
Q19i_WKS_Recode	=	"Recode: Marijuana/week	"
Q19j_WKS_Recode	=	"Recode: Cocaine/week	"

Q20	=	"	Around smoker, hours/day	"
Q21	=	"	People smoking in home	"

Q22	=	"	Work status changed, yes/no	"
Q22a1	=	"	Work status changed, duties	"
Q22a2	=	"	Work status changed, stress	"
Q22a3	=	"	Work status changed, employer	"
Q22a4	=	"	Work status changed, title	"
Q22a5	=	"	Work status changed, full/part time	"
Q22a6	=	"	Work status changed, stopped working	"
Q22a7	=	"	Work status changed, started working	"
Q22a8	=	"	Work status changed, other	"
Q22a9	=	"	Work status changed, shift	"
Q22b_a	=	"	Employment, cashier	"
Q22b_b	=	"	Employment, health care	"
Q22b_c	=	"	Employment, food service"
Q22b_d	=	"	Employment, none of the above	"
Q22b_e	=	"	Employment, hairdresser		"
Q22b1	=	"	Carbonless paper	"
Q22b2	=	"	Food service type	"
Q22b3_a	=	"	Hairdresser type, beautician	"
Q22b3_b	=	"	Hairdresser type, manicurist	"
Q22b3_c	=	"	Hairdresser type, colorist	"
Q22b3_d	=	"	Hairdresser type, other	"
Q22b4	=	"	Health care type	"

Q22b4_a	=	"	Health care, blood bags	"
Q22b4_b	=	"	Health care, CPB tubing	"
Q22b4_c	=	"	Health care, feeding bags	"
Q22b4_d	=	"	Health care, ECMO tubing	"
Q22b4_e	=	"	Health care, IV bags	"
Q22b4_f	=	"	Health care, hemodialysis tubing	"
Q22b4_g	=	"	Health care, NG tubes	"
Q22b4_h	=	"	Health care, umbilical artery catheters	"
Q22b4_i	=	"	Health care, dialysis bags	"
Q22b4_j	=	"	Health care, vinyl gloves	"

Q22c	=	"	Working hours	"
Q22d	=	"	Stressful job	"
Q22e	=	"	Supervise anyone	"
Q22e1	=	"	Subordinates supervise others	"
Q22f	=	"	Free to make decisions on job	"

Q23	    =	"	Hours in car	"
Q24	    =	"	How many sales receipts/day	"

Q25a    =   "   Renovations Non-toxic, yes or no: Painting rooms or exterior "
Q25b    =   "   Renovations: Non-toxic, yes or no: Refinishing floors "
Q25c    =   "   Renovations: Non-toxic, yes or no: Installing carpets "
Q25d    =   "   Renovations: Non-toxic, yes or no: Extermination "
Q25e    =   "   Renovations: Non-toxic, yes or no: Other major remodel "

Q26     =   "Age of father in years"
Q27_DAD_HEIGHT_DK = " Don't know height"
Q27_DAD_HEIGHT_FT = " Height of father in feet"     
Q27_DAD_HEIGHT_IN = " Height of father in inches"     
Q27_DAD_WEIGHT_DK = " Don't know weight"     
Q27_DAD_WEIGHT_LBS = " Weight of father in pounds"    
Q27_dad_height_recode  =  " Recoded height of father in inches"

Q28 = "Father ethnicity"
Q29 = "Father race"
Q30 = "Father's education"

Q31_YN  = 	"	Marital status changed, yes/no	"
Q31a	=	"	How has marital status changed	"
Q31b	=	"	Lived with spouse	"

Q32     =	"	Is there any one special person you feel close with/depend on	"
Q33     =	"	Are there people you feel at ease with an can talk to about private matters and trust to help you	"
Q34     =	"	How often do you wish you knew more people you could talk to	"
Q35     =	"	How often do you wish you knew more friends/relatives who could help you out	"
Q36     =	"	Would you say you've been overwhelmed by the thought of caring for the new baby	"

Q37_YN     =   "   You or your partner lost a job or was (were) unemployed for one month or longer: Yes or no"
Q37_T1  =   "   Job loss occur in first trimester: yes or no"
Q37_T2  =   "   Job loss occur in second trimester: yes or no"
Q37_T3  =   "   Job loss occur in third trimester: yes or no"

Q38_YN     =   "   Close family member had seriously illness or injury: Yes or no"
Q38_T1  =   "   Illness/injury in first trimester: yes or no"
Q38_T2  =   "   Illness/injury in second trimester: yes or no"
Q38_T3  =   "   Illness/injury in third trimester: yes or no"

Q39_YN     =   "   Death of a close family member: Yes or no"
Q39_T1  =   "   Death of a close family member in first trimester: yes or no"
Q39_T2  =   "   Death of a close family member in second trimester: yes or no"
Q39_T3  =   "   Death of a close family member in third trimester: yes or no"

Q40_YN     =   "   Were you separated, divorced or expereinced difficulties with your partner: Yes or no"
Q40_T1  =   "   Separation, divorce, partner difficulties in first trimester: yes or no"
Q40_T2  =   "   Separation, divorce, partner difficulties in second trimester: yes or no"
Q40_T3  =   "   Separation, divorce, partner difficulties in third trimester: yes or no"

Q41_YN     =   "   Did you/partner experience serious legal or financial problems: Yes or no"
Q41_T1  =   "   Legal or financial problems in first trimester: yes or no"
Q41_T2  =   "   Legal or financial problems in second trimester: yes or no"
Q41_T3  =   "   Legal or financial problems in third trimester: yes or no"

Q42_YN     =   "   Other major events: Yes or no"
Q42_T1  =   "   Other major events in first trimester: yes or no"
Q42_T2  =   "   Other major events in second trimester: yes or no"
Q42_T3  =   "   Other major events in third trimester: yes or no"

Q43 = " Reason for participating in TIDES"

TIME_STAMP	=	" TIME_STAMP:  ? ,with an interval time format"
TIME_END_RAW = " Time finished questionnaire, with an interval time format"   
TIME_STARTED_RAW = " Time started questionnaire, with an interval time format"
TIME_STARTED = " Time started questionnaire"
TIMECOMPLETED = " Time used to complete questionnaire"
;
